export const courses = [
    {
        id:1,
      name: 'AI for Beginners',
      description: 'An introduction to Artificial Intelligence for beginners.',
      price: 100,
      duration: 12,
      rating: 4.5,
      creator: 'John Doe',
      views: 2000,
      lessons: ['Introduction to AI', 'AI Basics', 'Machine Learning Overview', 'Simple AI Projects'],
      category: 'AI',
      difficulty: 'Beginner',
    },
    {
        id:2,
      name: 'Advanced Machine Learning',
      description: 'A comprehensive course on advanced machine learning techniques.',
      price: 200,
      duration: 20,
      rating: 4.8,
      creator: 'Jane Smith',
      views: 1500,
      lessons: ['Deep Learning', 'Neural Networks', 'Reinforcement Learning', 'Model Evaluation'],
      category: 'AI',
      difficulty: 'Advanced',
    },
    {
        id:3,
      name: 'Full-Stack Web Development',
      description: 'Become a full-stack developer with a focus on front-end and back-end.',
      price: 120,
      duration: 15,
      rating: 4.7,
      creator: 'Sarah Lee',
      views: 3000,
      lessons: ['HTML', 'CSS', 'JavaScript', 'Node.js', 'Express', 'MongoDB'],
      category: 'Web Development',
      difficulty: 'Intermediate',
    },
    {
        id:4,
      name: 'React for Beginners',
      description: 'Learn React.js and build modern web applications.',
      price: 90,
      duration: 10,
      rating: 4.6,
      creator: 'Tom Brown',
      views: 2200,
      lessons: ['React Basics', 'State Management', 'React Router','Videos', 'React Hooks'],
      category: 'Web Development',
      difficulty: 'Beginner',
    },
    {   
        id:5,
      name: 'Deep Learning with Python',
      description: 'Learn deep learning techniques using Python and TensorFlow.',
      price: 250,
      duration: 25,
      rating: 4.9,
      creator: 'Michael Chen',
      views: 1000,
      lessons: ['Neural Networks', 'Convolutional Networks', 'Recurrent Networks', 'TensorFlow Basics'],
      category: 'AI',
      difficulty: 'Advanced',
    },
    {
        id:6,
      name: 'Personal Finance for Beginners',
      description: 'Learn how to manage personal finances and grow wealth.',
      price: 80,
      duration: 8,
      rating: 4.4,
      creator: 'Daniel Davis',
      views: 4000,
      lessons: ['Budgeting', 'Investing Basics', 'Debt Management', 'Saving Tips'],
      category: 'Finance',
      difficulty: 'Beginner',
    },
    {
        id:7,
      name: 'Professional Networking for Career Growth',
      description: 'Learn the essential skills for building a professional network.',
      price: 60,
      duration: 5,
      rating: 4.2,
      creator: 'Emily Green',
      views: 1500,
      lessons: ['Networking Basics', 'LinkedIn Mastery', 'Building Relationships', 'Effective Communication'],
      category: 'Career Development',
      difficulty: 'Beginner',
    },
    {
        id:8,
      name: 'Blockchain and Cryptocurrency Basics',
      description: 'Understand the fundamentals of blockchain technology and cryptocurrencies.',
      price: 130,
      duration: 18,
      rating: 4.7,
      creator: 'Robert King',
      views: 3500,
      lessons: ['Blockchain Basics', 'Bitcoin and Ethereum', 'Smart Contracts', 'Decentralized Finance'],
      category: 'Blockchain',
      difficulty: 'Intermediate',
    },
    {
        id:9,
      name: 'Leadership and Management Skills',
      description: 'Develop leadership and management skills for career growth.',
      price: 150,
      duration: 12,
      rating: 4.6,
      creator: 'Linda White',
      views: 1700,
      lessons: ['Leadership Styles', 'Conflict Resolution', 'Team Management', 'Effective Decision Making'],
      category: 'Career Development',
      difficulty: 'Intermediate',
    },
    {
        id:10,
      name: 'AI for Career Growth',
      description: 'Learn how AI can enhance your career in various fields.',
      price: 200,
      duration: 18,
      rating: 4.7,
      creator: 'Sophia Lee',
      views: 2100,
      lessons: ['AI Applications', 'AI in Industry', 'Building AI Projects', 'AI for Personal Growth'],
      category: 'AI',
      difficulty: 'Intermediate',
    },
  ];